# Generated by Django 4.1.3 on 2023-02-01 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.CharField(choices=[('AD', 'Администратор'), ('MD', 'Модератор'), ('LA', 'Библиотекарь'), ('OU', 'Пользователь')], default='OU', max_length=2, verbose_name='Роль пользователя')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Адрес')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_action', models.DateTimeField(auto_now=True, verbose_name='Последние действия')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
